blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/ShreyashSaitwal/rush-cli/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
