package com.google.appinventor.components.common

/**
 * Contains constants related to the persistent format of Simple components.
 */
object ComponentConstants {
    /**
     * App constants
     */
    const val APP_INVENTOR_MIN_SDK = 7

    /**
     * Layout constants.
     */
    const val LAYOUT_ORIENTATION_HORIZONTAL = 0
    const val LAYOUT_ORIENTATION_VERTICAL = 1
    const val DEFAULT_ROW_COLUMN = -1
    const val EMPTY_HV_ARRANGEMENT_WIDTH = 100
    const val EMPTY_HV_ARRANGEMENT_HEIGHT = 100

    /**
     * Canvas component.
     */
    const val CANVAS_PREFERRED_WIDTH = 32
    const val CANVAS_PREFERRED_HEIGHT = 48

    /**
     * VideoPlayer component.
     * This is the size generated by iMovie for small videos
     */
    const val VIDEOPLAYER_PREFERRED_WIDTH = 176
    const val VIDEOPLAYER_PREFERRED_HEIGHT = 144

    /**
     * TextBox, PasswordTextBox, and EmailPicker components.
     */
    const val TEXTBOX_PREFERRED_WIDTH = 160

    /**
     * HorizontalArrangement, VerticalArrangement, and Screen
     */
    const val GRAVITY_LEFT = 1
    const val GRAVITY_RIGHT = 2
    const val GRAVITY_CENTER_HORIZONTAL = 3
    const val GRAVITY_TOP = 1
    const val GRAVITY_CENTER_VERTICAL = 2
    const val GRAVITY_BOTTOM = 3
    const val HORIZONTAL_ALIGNMENT_DEFAULT = GRAVITY_LEFT
    const val VERTICAL_ALIGNMENT_DEFAULT = GRAVITY_TOP
    const val TEXT_RECEIVING_OFF = 1
    const val TEXT_RECEIVING_FOREGROUND = 2
    const val TEXT_RECEIVING_ALWAYS = 3

    /**
     * ListView component.
     */
    const val LISTVIEW_PREFERRED_WIDTH = 315
    const val LISTVIEW_PREFERRED_HEIGHT = 40
    const val LISTVIEW_FILTER_PREFERRED_HEIGHT = 30

    /**
     * Scrollable Arrangements
     */
    @JvmField
    var SCROLLABLE_ARRANGEMENT = true

    @JvmField
    var NONSCROLLABLE_ARRANGEMENT = false

    /**
     * Themeing
     */
    const val DEFAULT_THEME = "Classic"
    const val DEFAULT_PRIMARY_COLOR = "&HFF3F51B5"
    const val DEFAULT_PRIMARY_DARK_COLOR = "&HFF303F9F"
    const val DEFAULT_ACCENT_COLOR = "&HFFFF4081"

    /**
     * Map Components
     */
    const val MAP_PREFERRED_WIDTH = 176
    const val MAP_PREFERRED_HEIGHT = 144
    const val MARKER_PREFERRED_WIDTH = 30
    const val MARKER_PREFERRED_HEIGHT = 50
    const val CIRCLE_PREFERRED_RADIUS = 30
    const val LINESTRING_PREFERRED_LENGTH = 60
    const val POLYGON_PREFERRED_WIDTH = 50
    const val POLYGON_PREFERRED_HEIGHT = 30
    const val RECTANGLE_PREFERRED_WIDTH = 50
    const val RECTANGLE_PREFERRED_HEIGHT = 30
}
