String getDotClasspath() {
  return '''
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="lib" path=".rush/dev_deps/acra-4.4.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/androidsvg.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/annotations-v186a.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/Barcode.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/commons-pool.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/CommonVersion.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/firebase.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/fusiontables.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/gson-2.1.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/guava-14.0.1.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/http-legacy.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/httpmime.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/jedis.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/json.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/kawa.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/osmdroid.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/physicaloid.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/QRGenerator.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/runtime-v186a.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/twitter4j.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/twitter4jmedia.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/webrtc.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/android.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/annotation-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/appcompat-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/asynclayoutinflater-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/collection-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/constraintlayout-1.1.3.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/constraintlayout-solver-1.1.3.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/coordinatorlayout-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/core-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/core-common-2.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/core-runtime-2.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/cursoradapter-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/customview-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/documentfile-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/drawerlayout-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/fragment-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/interpolator-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/lifecycle-common-2.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/lifecycle-livedata-2.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/lifecycle-livedata-core-2.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/lifecycle-runtime-2.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/lifecycle-viewmodel-2.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/loader-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/localbroadcastmanager-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/print-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/slidingpanelayout-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/swiperefreshlayout-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/testing-support-R-classes.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/vectordrawable-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/vectordrawable-animated-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/versionedparcelable-1.0.0.jar"/>
	<classpathentry kind="lib" path=".rush/dev_deps/android/viewpager-1.0.0.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
''';
}
